import { Injectable, signal, computed, effect, inject, untracked } from '@angular/core';
import {
  IBodyPartIssue,
  IPatientVitals,
  IBiometricEntry,
  IClinicalNote,
  IChecklistItem,
  IShoppingListItem,
  IDraftSummaryItem,
  IPatientState,
  HistoryEntry,
  IBookmark,
  BODY_PART_NAMES,
  BODY_PART_MAPPING,
  IAyurvedicStatus
} from './patient.types';

export type { IPatientState };
export { BODY_PART_NAMES };
import { StorageService } from './storage.service';
import { GamificationService } from './gamification.service';
import { ThemeService } from './theme.service';


@Injectable({
  providedIn: 'root'
})
export class PatientStateService {
  // --- UI State ---
  readonly selectedPartId = signal<string | null>(null);
  readonly selectedNoteId = signal<string | null>(null);
  readonly isLiveAgentActive = signal<boolean>(false);
  readonly liveAgentInput = signal<string>('');
  readonly isResearchFrameVisible = signal<boolean>(false);
  readonly analysisUpdateRequest = signal(0);
  readonly requestedResearchUrl = signal<string | null>(null);
  readonly requestedResearchQuery = signal<string | null>(null);
  readonly requestedSearchEngine = signal<'google' | 'pubmed' | null>(null);
  readonly viewingPastVisit = signal<HistoryEntry | null>(null);
  readonly bodyViewerMode = signal<'3d' | '2d'>('3d');
  readonly anatomyViewMode = signal<'skin' | 'muscle' | 'skeleton' | 'organs' | 'molecular'>('skin');
  readonly activePatientSummary = signal<string | null>(null);
  readonly draftSummaryItems = signal<IDraftSummaryItem[]>([]);
  /** AI-derived anatomical findings mapped to severity tier for 3D overlay. */
  readonly aiAnomalyHighlights = signal<Record<string, 'critical' | 'moderate' | 'mild'>>({});
  /** Toggle the semi-transparent reference mannequin ghost overlay. */
  readonly showGhostOverlay = signal<boolean>(false);
  readonly lensAnnotations = signal<Record<string, Record<string, any>>>({});
  readonly isEmergencyMode = signal<boolean>(false);
  readonly isDemoMode = signal<boolean>(false);
  readonly activePhilosophy = signal<'western' | 'eastern' | 'ayurvedic'>('western');

  // --- AVS Neuro-Therapy Synchronized State ---
  readonly isAvsSessionActive = signal<boolean>(false);
  readonly avsBreathingRate = signal<number>(6.0);
  readonly avsBrainwaveFrequency = signal<string>('theta');
  /** AI-generated contextual co-regulation protocol for this encounter. */
  readonly avsProtocol = signal<import('./patient.types').IAvsProtocol | null>(null);
  /** Is the contextual protocol currently being generated by Gemini? */
  readonly isGeneratingAvsProtocol = signal<boolean>(false);

  // --- Patient Contextual State (feeds Co-Regulation AVS) ---
  /** Patient's occupational category — informs autonomic baseline and AVS protocol selection. */
  readonly occupation = signal<string>('');
  /** Chief complaint / reason for this specific encounter. */
  readonly reasonForVisit = signal<string>('');
  /** Dietary Protocol / Nutrition Strategy to integrate into intake */
  readonly dietaryProtocol = signal<string>('');
  /** Trauma safety flags extracted from chart — gates AVS protocol selection. */
  readonly traumaFlags = signal<import('./patient.types').ITraumaFlags | null>(null);

  // --- Patient Data State ---
  readonly issues = signal<Record<string, IBodyPartIssue[]>>({});
  readonly patientGoals = signal<string>("");
  readonly    vitals = signal<IPatientVitals>({
        bp: '',
        hr: '',
        temp: '',
        spO2: '',
        weight: '',
        height: '',
        vitC: '',
        vitD3: '',
        magnesium: '',
        zinc: '',
        b12: ''
    });

    readonly dynamicNutrients = signal<import('./patient.types').IDynamicMarker[]>([]);
  readonly oxidativeStressMarkers = signal<import('./patient.types').IDynamicMarker[]>([]);
  readonly antioxidantSources = signal<import('./patient.types').IDynamicMarker[]>([]);
  readonly medications = signal<import('./patient.types').IDynamicMarker[]>([]);
  
  readonly clinicalNotes = signal<IClinicalNote[]>([]);
  readonly checklist = signal<IChecklistItem[]>([]);
  readonly shoppingList = signal<IShoppingListItem[]>([]);
  readonly biometricHistory = signal<IBiometricEntry[]>([]);
  readonly ayurvedicStatus = signal<IAyurvedicStatus>({});

  // A trigger to force the UI to expand the analysis panel when an item is selected/clicked
  readonly uiExpandTrigger = signal<number>(0);

  private storage = inject(StorageService);
  private game = inject(GamificationService);
  private themeService = inject(ThemeService);

  readonly isSparkModeActive = computed(() => this.themeService.currentTheme() === 'spark');

  constructor() {
    if (typeof window !== 'undefined') {
      // 1. Hydrate state asynchronously on app load
      this.storage.loadState('current_patient').then(data => {
        if (data && data.state) {
          // Temporarily disable the effect by untracking the init load (if needed), 
          // but loadState() mutations will just trigger a re-save, which is safe.
          this.loadState(data.state);
        }
      });

      // 2. Persist state on any signal mutation
      effect(() => {
        const currentState = this.getCurrentState();
        const isEmergency = this.isEmergencyMode();
        untracked(() => {
          if (!isEmergency) {
            this.storage.saveState('current_patient', currentState);
          }
        });
      });
    }
  }

  // --- Computed State ---
  readonly hasIssues = computed(() =>
    Object.keys(this.issues()).length > 0 || this.patientGoals().length > 0
  );

  readonly inferredAyurvedicTriage = computed(() => {
    const manual = this.ayurvedicStatus();
    const inferred = this.runAyurvedicInference(this.issues(), this.vitals(), this.patientGoals(), this.dietaryProtocol());
    return {
      prakriti: manual.prakriti || inferred.prakriti,
      vikriti: manual.vikriti || inferred.vikriti,
      agniStatus: manual.agniStatus || inferred.agniStatus,
      amaStatus: manual.amaStatus || inferred.amaStatus,
      affectedDhatus: manual.affectedDhatus?.length ? manual.affectedDhatus : inferred.affectedDhatus,
      blockedSrotas: manual.blockedSrotas?.length ? manual.blockedSrotas : inferred.blockedSrotas,
      dominantGunas: manual.dominantGunas?.length ? manual.dominantGunas : inferred.dominantGunas
    };
  });

  runAyurvedicInference(
    issues: Record<string, IBodyPartIssue[]>,
    vitals: IPatientVitals,
    goals: string,
    diet: string
  ): IAyurvedicStatus {
    const goalsLower = goals.toLowerCase();
    const dietLower = diet.toLowerCase();
    const allNotes = Object.values(issues).flat();
    const notesLower = allNotes.map(i => i.description.toLowerCase()).join(' ');

    const hrNum = parseInt(vitals.hr, 10) || 0;
    const tempNum = parseFloat(vitals.temp) || 0;
    const systolic = parseInt(vitals.bp.split('/')[0], 10) || 0;

    let vataScore = 0;
    let pittaScore = 0;
    let kaphaScore = 0;

    // Vata Triggers
    if (hrNum > 90) vataScore += 2;
    if (allNotes.some(i => i.painLevel >= 6)) vataScore += 2;
    const vataKeywords = ['dry', 'stiffness', 'neuropathic', 'sciatic', 'insomnia', 'anxiety', 'constipation', 'cracking', 'pain', 'dryness', 'roughness'];
    vataKeywords.forEach(kw => {
      if (goalsLower.includes(kw)) vataScore += 1;
      if (notesLower.includes(kw)) vataScore += 1;
      if (dietLower.includes(kw)) vataScore += 1;
    });

    // Pitta Triggers
    if (tempNum > 99 || (tempNum > 37.2 && tempNum < 45)) pittaScore += 2;
    if (systolic > 130) pittaScore += 2;
    const pittaKeywords = ['burning', 'inflammation', 'acid', 'reflux', 'fever', 'redness', 'rash', 'sharp', 'heartburn', 'heat', 'acidity', 'loose stool'];
    pittaKeywords.forEach(kw => {
      if (goalsLower.includes(kw)) pittaScore += 1;
      if (notesLower.includes(kw)) pittaScore += 1;
      if (dietLower.includes(kw)) pittaScore += 1;
    });

    // Kapha Triggers
    if (vitals.weight && parseInt(vitals.weight, 10) > 200) kaphaScore += 2;
    const kaphaKeywords = ['sluggish', 'edema', 'heavy', 'congestion', 'swelling', 'mucus', 'lethargy', 'retention', 'heaviness', 'slow', 'moist'];
    kaphaKeywords.forEach(kw => {
      if (goalsLower.includes(kw)) kaphaScore += 1;
      if (notesLower.includes(kw)) kaphaScore += 1;
      if (dietLower.includes(kw)) kaphaScore += 1;
    });

    // Determine Vikriti (Imbalance)
    let vikriti = '';
    const scores = [{ dosha: 'Vata', score: vataScore }, { dosha: 'Pitta', score: pittaScore }, { dosha: 'Kapha', score: kaphaScore }];
    scores.sort((a, b) => b.score - a.score);
    if (scores[0].score === 0) {
      vikriti = 'Tridosha (Balanced)';
    } else if (scores[0].score - scores[1].score <= 1 && scores[1].score > 0) {
      vikriti = `${scores[0].dosha}-${scores[1].dosha} Aggravation`;
    } else {
      vikriti = `${scores[0].dosha} Aggravation`;
    }

    // Determine Agni Status
    let agniStatus: 'Sama' | 'Vishama' | 'Tikshna' | 'Manda' = 'Sama';
    if (vataScore > pittaScore && vataScore > kaphaScore && vataScore > 0) {
      agniStatus = 'Vishama';
    } else if (pittaScore > vataScore && pittaScore > kaphaScore && pittaScore > 0) {
      agniStatus = 'Tikshna';
    } else if (kaphaScore > vataScore && kaphaScore > pittaScore && kaphaScore > 0) {
      agniStatus = 'Manda';
    }

    // Determine Ama Status
    let amaStatus: 'Nirama' | 'Sama' = 'Nirama';
    const amaKeywords = ['stiffness', 'fatigue', 'coated tongue', 'sluggishness', 'brain fog', 'heaviness', 'constipation', 'mucus'];
    let amaMatches = 0;
    amaKeywords.forEach(kw => {
      if (goalsLower.includes(kw) || notesLower.includes(kw)) amaMatches++;
    });
    if (amaMatches >= 2 || kaphaScore > 4) {
      amaStatus = 'Sama';
    }

    // Determine affected Dhatus
    const affectedDhatus: ('Rasa' | 'Rakta' | 'Mamsa' | 'Medas' | 'Asthi' | 'Majja' | 'Shukra')[] = [];
    if (notesLower.includes('skin') || notesLower.includes('fatigue') || notesLower.includes('lymph') || goalsLower.includes('energy')) {
      affectedDhatus.push('Rasa');
    }
    if (notesLower.includes('blood') || notesLower.includes('pressure') || notesLower.includes('rash') || notesLower.includes('inflammation') || notesLower.includes('redness')) {
      affectedDhatus.push('Rakta');
    }
    if (notesLower.includes('muscle') || notesLower.includes('spasm') || notesLower.includes('wasting') || notesLower.includes('shoulder') || notesLower.includes('arm')) {
      affectedDhatus.push('Mamsa');
    }
    if (notesLower.includes('weight') || notesLower.includes('fat') || notesLower.includes('metabolism') || notesLower.includes('cholesterol')) {
      affectedDhatus.push('Medas');
    }
    if (notesLower.includes('joint') || notesLower.includes('bone') || notesLower.includes('sciatic') || notesLower.includes('back') || notesLower.includes('stiffness')) {
      affectedDhatus.push('Asthi');
    }
    if (notesLower.includes('nerve') || notesLower.includes('neuropathic') || notesLower.includes('sleep') || notesLower.includes('insomnia') || notesLower.includes('anxiety')) {
      affectedDhatus.push('Majja');
    }
    if (notesLower.includes('hormone') || notesLower.includes('libido') || notesLower.includes('vitality') || notesLower.includes('fertility')) {
      affectedDhatus.push('Shukra');
    }

    // Determine blocked Srotas
    const blockedSrotas: string[] = [];
    if (notesLower.includes('cough') || notesLower.includes('breath') || notesLower.includes('lungs') || notesLower.includes('congestion')) {
      blockedSrotas.push('Pranavaha Srotas (Respiratory)');
    }
    if (notesLower.includes('stomach') || notesLower.includes('acid') || notesLower.includes('reflux') || notesLower.includes('digestion') || notesLower.includes('nausea') || notesLower.includes('bloating')) {
      blockedSrotas.push('Annavaha Srotas (Digestive)');
    }
    if (notesLower.includes('swelling') || notesLower.includes('edema') || notesLower.includes('water') || notesLower.includes('retention')) {
      blockedSrotas.push('Udakavaha Srotas (Water regulation)');
    }
    if (affectedDhatus.includes('Rasa')) {
      blockedSrotas.push('Rasavaha Srotas (Plasma/Lymphatic)');
    }
    if (affectedDhatus.includes('Rakta')) {
      blockedSrotas.push('Raktavaha Srotas (Circulatory)');
    }
    if (affectedDhatus.includes('Asthi')) {
      blockedSrotas.push('Asthivaha Srotas (Skeletal)');
    }
    if (affectedDhatus.includes('Majja')) {
      blockedSrotas.push('Majjavaha Srotas (Nervous)');
    }

    // Determine dominant Gunas
    const dominantGunas: string[] = [];
    if (vataScore > 2) {
      dominantGunas.push('Ruksha (Dry)', 'Sheeta (Cold)', 'Chala (Mobile)');
    }
    if (pittaScore > 2) {
      dominantGunas.push('Ushna (Hot)', 'Tikshna (Sharp)', 'Sara (Spreading)');
    }
    if (kaphaScore > 2) {
      dominantGunas.push('Guru (Heavy)', 'Manda (Slow)', 'Sheeta (Cold)');
    }

    return {
      prakriti: 'Tridosha',
      vikriti,
      agniStatus,
      amaStatus,
      affectedDhatus,
      blockedSrotas,
      dominantGunas
    };
  }

  readonly selectedPartName = computed(() => {
    const id = this.selectedPartId();
    if (!id) return null;
    return BODY_PART_NAMES[id] || id;
  });

  // Helper to check if a part has any notes
  hasIssue(partId: string): boolean {
    const issues = this.issues()[partId];
    return !!issues && issues.length > 0;
  }

  // Helper to check if a part has a note with a pain level > 0
  hasPainfulIssue(partId: string): boolean {
    const issues = this.issues()[partId];
    return !!issues && issues.some(i => i.painLevel > 0);
  }

  // --- Actions ---
  triggerUiExpand() {
    this.uiExpandTrigger.set(Date.now());
  }

  selectPart(partId: string | null) {
    this.selectedPartId.set(partId);
    this.triggerUiExpand();
    if (!partId) {
      this.selectedNoteId.set(null); // Deselect note when part is deselected
    } else {
      this.game.completeQuest('click_anatomy');
    }
  }

  selectNote(noteId: string | null) {
    this.selectedNoteId.set(noteId);
  }

  selectPhilosophy(philosophy: 'western' | 'eastern' | 'ayurvedic') {
    this.activePhilosophy.set(philosophy);
    this.requestAnalysisUpdate();
  }

  toggleLiveAgent(active: boolean) {
    this.isLiveAgentActive.set(active);
  }

  toggleResearchFrame(visible?: boolean) {
    if (visible === undefined) {
      this.isResearchFrameVisible.update(v => {
        const next = !v;
        if (next) this.game.completeQuest('explore_evidence');
        return next;
      });
    } else {
      this.isResearchFrameVisible.set(visible);
      if (visible) {
        this.game.completeQuest('explore_evidence');
      }
    }
  }

  updateIssue(partId: string, issue: IBodyPartIssue) {
    this.issues.update(current => {
      const issuesForPart = current[partId] ? [...current[partId]] : [];
      const existingIndex = issuesForPart.findIndex(i => i.noteId === issue.noteId);
      if (existingIndex > -1) {
        // Update existing issue
        issuesForPart[existingIndex] = issue;
      } else {
        // Add new issue
        issuesForPart.push(issue);
      }
      return {
        ...current,
        [partId]: issuesForPart
      };
    });
  }

  removeIssueNote(partId: string, noteId: string) {
    this.issues.update(current => {
      const issuesForPart = current[partId] || [];
      const updatedIssuesForPart = issuesForPart.filter(i => i.noteId !== noteId);
      const updated = { ...current };
      if (updatedIssuesForPart.length > 0) {
        updated[partId] = updatedIssuesForPart;
      } else {
        // If no issues are left for this part, remove the part key
        delete updated[partId];
      }
      return updated;
    });
  }

  updateGoals(goals: string) {
    this.patientGoals.set(goals);
  }

    updateVital(key: keyof IPatientVitals, value: string) {
        this.vitals.update(vitals => ({ ...vitals, [key]: value }));
    }

    addDynamicNutrient() {
        this.dynamicNutrients.update(nutrients => [
            ...nutrients, 
            { id: Date.now().toString(), name: '', value: '' }
        ]);
    }

    updateDynamicNutrient(id: string, field: 'name' | 'value', value: string) {
        this.dynamicNutrients.update(nutrients => 
            nutrients.map(n => n.id === id ? { ...n, [field]: value } : n)
        );
    }

    removeDynamicNutrient(id: string) {
        this.dynamicNutrients.update(nutrients => nutrients.filter(n => n.id !== id));
    }
    
    // --- Oxidative Stress Markers ---
    addOxidativeStressMarker() {
        this.oxidativeStressMarkers.update(markers => [
            ...markers, 
            { id: Date.now().toString(), name: '', value: '' }
        ]);
    }

    updateOxidativeStressMarker(id: string, field: 'name' | 'value', value: string) {
        this.oxidativeStressMarkers.update(markers => 
            markers.map(n => n.id === id ? { ...n, [field]: value } : n)
        );
    }

    removeOxidativeStressMarker(id: string) {
        this.oxidativeStressMarkers.update(markers => markers.filter(n => n.id !== id));
    }

    // --- Antioxidant Sources ---
    addAntioxidantSource() {
        this.antioxidantSources.update(sources => [
            ...sources, 
            { id: Date.now().toString(), name: '', value: '' }
        ]);
    }

    updateAntioxidantSource(id: string, field: 'name' | 'value', value: string) {
        this.antioxidantSources.update(sources => 
            sources.map(n => n.id === id ? { ...n, [field]: value } : n)
        );
    }

    removeAntioxidantSource(id: string) {
        this.antioxidantSources.update(sources => sources.filter(n => n.id !== id));
    }

    // --- Medications ---
    addMedication() {
        this.medications.update(meds => [
            ...meds, 
            { id: Date.now().toString(), name: '', value: '' }
        ]);
    }

    updateMedication(id: string, field: 'name' | 'value', value: string) {
        this.medications.update(meds => 
            meds.map(n => n.id === id ? { ...n, [field]: value } : n)
        );
    }

    removeMedication(id: string) {
        this.medications.update(meds => meds.filter(n => n.id !== id));
    }
  updateActivePatientSummary(plan: string | null) {
    this.activePatientSummary.set(plan);
  }

  // --- Biometric Data Actions ---
  addBiometricEntries(entries: IBiometricEntry[]) {
    this.biometricHistory.update(history => [...history, ...entries]);
  }

  clearBiometricHistory() {
    this.biometricHistory.set([]);
  }

  // --- Care Plan Drafting Actions ---
  addClinicalNote(note: IClinicalNote) {
    this.clinicalNotes.update(notes => {
      const existing = notes.findIndex(n => n.id === note.id);
      if (existing > -1) {
        const next = [...notes];
        next[existing] = note;
        return next;
      }
      return [...notes, note];
    });
  }

  removeClinicalNote(id: string) {
    this.clinicalNotes.update(notes => notes.filter(n => n.id !== id));
  }

  addDraftSummaryItem(id: string, text: string) {
    this.draftSummaryItems.update(items => {
      const existing = items.findIndex(i => i.id === id);
      if (existing > -1) {
        const next = [...items];
        next[existing] = { id, text };
        return next;
      }
      return [...items, { id, text }];
    });
  }

  addChecklistItem(item: IChecklistItem) {
    this.checklist.update(items => [...items, item]);
  }

  toggleChecklistItem(id: string) {
    this.checklist.update(items => items.map(item =>
      item.id === id ? { ...item, completed: !item.completed } : item
    ));
  }

  removeChecklistItem(id: string) {
    this.checklist.update(items => items.filter(item => item.id !== id));
  }

  addShoppingListItem(item: IShoppingListItem) {
    this.shoppingList.update(items => [...items, item]);
  }

  toggleShoppingListItem(id: string) {
    this.shoppingList.update(items => items.map(item =>
      item.id === id ? { ...item, completed: !item.completed } : item
    ));
  }

  removeShoppingListItem(id: string) {
    this.shoppingList.update(items => items.filter(item => item.id !== id));
  }

  removeDraftSummaryItem(id: string) {
    this.draftSummaryItems.update(items => items.filter(item => item.id !== id));
  }

  clearDraftSummaryItems() {
    this.draftSummaryItems.set([]);
  }

  requestAnalysisUpdate() {
    this.analysisUpdateRequest.update(v => v + 1);
  }

  requestResearchUrl(url: string) {
    this.requestedResearchUrl.set(url);
  }

  requestResearchSearch(query: string, engine?: 'google' | 'pubmed') {
    if (engine) {
      this.requestedSearchEngine.set(engine);
    }
    this.requestedResearchQuery.set(query);
    this.toggleResearchFrame(true);
  }

  setViewingPastVisit(visit: HistoryEntry | null) {
    this.viewingPastVisit.set(visit);
  }


  // --- State Management for Multi-Patient ---

  /** Clears all patient data to represent a clean slate. */
  clearState() {
    this.selectedPartId.set(null);
    this.selectedNoteId.set(null);
    this.isLiveAgentActive.set(false); // also end any active consult
    this.isResearchFrameVisible.set(false);
    this.aiAnomalyHighlights.set({});
    this.showGhostOverlay.set(false);
    this.issues.set({});
    this.patientGoals.set('');
    this.dietaryProtocol.set('');
        this.vitals.set({
            bp: '', hr: '', temp: '', spO2: '', weight: '', height: '',
            vitC: '', vitD3: '', magnesium: '', zinc: '', b12: ''
        });
        this.dynamicNutrients.set([]);
        this.oxidativeStressMarkers.set([]);
        this.antioxidantSources.set([]);
        this.medications.set([]);
    this.clinicalNotes.set([]);
    this.checklist.set([]);
    this.shoppingList.set([]);
    this.activePatientSummary.set(null);
    this.draftSummaryItems.set([]);
    this.biometricHistory.set([]);
    this.requestedResearchUrl.set(null);
    this.requestedResearchQuery.set(null);
    this.requestedSearchEngine.set(null);
    this.viewingPastVisit.set(null);
    this.activePhilosophy.set('western');
    this.ayurvedicStatus.set({});
  }

  /** Set AI-detected anomaly highlights on body parts. Called after analysis completes. */
  setAiAnomalyHighlights(highlights: Record<string, 'critical' | 'moderate' | 'mild'>) {
    this.aiAnomalyHighlights.set(highlights);
  }

  /** Remove all AI anomaly overlay markers from the 3D viewer. */
  clearAiAnomalyHighlights() {
    this.aiAnomalyHighlights.set({});
  }

  /** Clears only patient data, leaving UI state intact, for review mode */
  clearIssuesAndGoalsForReview() {
    this.selectedPartId.set(null);
    this.selectedNoteId.set(null);
    this.issues.set({});
    this.patientGoals.set('');
    this.draftSummaryItems.set([]);
    // Do not clear clinicalNotes or checklist here
  }

  /** Loads the state of a specific patient. */
  loadState(state: IPatientState) {
    this.clearState(); // Start from a clean slate
    this.issues.set(state.issues);
        if (state.patientGoals) this.patientGoals.set(state.patientGoals);
        if (state.dietaryProtocol) this.dietaryProtocol.set(state.dietaryProtocol);
        if (state.vitals) this.vitals.set(state.vitals);
        if (state.dynamicNutrients) this.dynamicNutrients.set(state.dynamicNutrients);
        if (state.oxidativeStressMarkers) this.oxidativeStressMarkers.set(state.oxidativeStressMarkers);
        if (state.antioxidantSources) this.antioxidantSources.set(state.antioxidantSources);
        if (state.medications) this.medications.set(state.medications);
    this.clinicalNotes.set(state.clinicalNotes || []);
    this.checklist.set(state.checklist || []);
    this.shoppingList.set(state.shoppingList || []);
    this.viewingPastVisit.set(null); // Ensure we're not in review mode when loading a patient.
    if (state.activePhilosophy) this.activePhilosophy.set(state.activePhilosophy);
    if (state.ayurvedicStatus) this.ayurvedicStatus.set(state.ayurvedicStatus);
  }

  /** Returns the current patient state for saving. */
  getCurrentState(): IPatientState {
    return {
            issues: this.issues(),
            patientGoals: this.patientGoals(),
            dietaryProtocol: this.dietaryProtocol(),
            vitals: this.vitals(),
            dynamicNutrients: this.dynamicNutrients(),
            oxidativeStressMarkers: this.oxidativeStressMarkers(),
            antioxidantSources: this.antioxidantSources(),
            medications: this.medications(),
            clinicalNotes: this.clinicalNotes(),
            checklist: this.checklist(),
            shoppingList: this.shoppingList(),
            activePhilosophy: this.activePhilosophy(),
            ayurvedicStatus: this.ayurvedicStatus(),
        };
  }


  // --- Data Aggregation ---
  getAllDataForPrompt(patientHistory: HistoryEntry[] = [], bookmarks: IBookmark[] = []): string {
    const issues = this.issues();
    const vitals = this.vitals();
    const carePlan = this.activePatientSummary();

    // 1. Current Issues
    const partsText = Object.values(issues).flat().map((i: IBodyPartIssue) =>
      `- Body Part: ${i.name}, Pain Level: ${i.painLevel}/10, Description: ${i.description}`
    ).join('\n');

    // 2. IVitals
    const vitalsText = `
    - BP: ${vitals.bp || 'N/A'}
    - HR: ${vitals.hr || 'N/A'}
    - Temp: ${vitals.temp || 'N/A'}
    - SpO2: ${vitals.spO2 || 'N/A'}
    - Weight: ${vitals.weight || 'N/A'}, Height: ${vitals.height || 'N/A'}
- Vitamin C: ${vitals.vitC || 'N/A'}
- Vitamin D3: ${vitals.vitD3 || 'N/A'}
- Magnesium: ${vitals.magnesium || 'N/A'}
- Zinc: ${vitals.zinc || 'N/A'}
- Vitamin B12: ${vitals.b12 || 'N/A'}

Dynamic Nutrients:
${this.dynamicNutrients().length > 0 ? this.dynamicNutrients().map(m => `- ${m.name}: ${m.value}`).join('\n') : 'None recorded'}

Oxidative Stress Markers:
${this.oxidativeStressMarkers().length > 0 ? this.oxidativeStressMarkers().map(m => `- ${m.name}: ${m.value}`).join('\n') : 'None recorded'}

Antioxidant Sources:
${this.antioxidantSources().length > 0 ? this.antioxidantSources().map(m => `- ${m.name}: ${m.value}`).join('\n') : 'None recorded'}

Active Medications:
${this.medications().length > 0 ? this.medications().map(m => `- ${m.name}: ${m.value}`).join('\n') : 'None recorded'}

Pain Areas:   `;

    // 3. Historical Context (Last 3 visits and recent notes)
    const recentHistory = patientHistory
      .filter(h => h.type === 'Visit' || h.type === 'NoteCreated' || h.type === 'BookmarkAdded')
      .slice(0, 5) // Limit to last 5 relevant entries to keep context manageable
      .map(h => {
        if (h.type === 'Visit') return `- Visit (${h.date}): ${h.summary}`;
        if (h.type === 'NoteCreated') return `- Note (${h.date}): ${h.summary}`;
        if (h.type === 'BookmarkAdded') return `- IBookmark (${h.date}): ${h.summary}`;
        return '';
      }).join('\n');

    // 4. Research Context & Bookmarks
    const citedBookmarks = bookmarks.filter(b => b.cited);
    const bookmarksText = bookmarks.map(b =>
      `- [${b.cited ? 'CITED' : 'Reference'}] ${b.title}: ${b.url}${b.authors ? ` (Authors: ${b.authors})` : ''}${b.doi ? ` (DOI: ${b.doi})` : ''}`
    ).join('\n');

    const ayurvedicTriage = this.inferredAyurvedicTriage();
    const ayurvedicText = `
    Inferred Ayurvedic Diagnostic Matrix:
    - Base Constitution (Prakriti): ${ayurvedicTriage.prakriti || 'N/A'}
    - Imbalance/Current State (Vikriti): ${ayurvedicTriage.vikriti || 'N/A'}
    - Digestion/Metabolic Fire (Agni): ${ayurvedicTriage.agniStatus || 'N/A'}
    - Toxic Load (Ama): ${ayurvedicTriage.amaStatus || 'N/A'}
    - Compromised Tissue Layers (Dhatus): ${ayurvedicTriage.affectedDhatus?.join(', ') || 'None inferred'}
    - Compromised Channels (Srotas): ${ayurvedicTriage.blockedSrotas?.join(', ') || 'None inferred'}
    - Active Qualities (Gunas): ${ayurvedicTriage.dominantGunas?.join(', ') || 'None inferred'}
    `;

    let prompt = `
    Patient Goals/Chief Complaint: ${this.patientGoals()}
    
    Dietary & Nutrition Intake: ${this.dietaryProtocol() || 'None provided'}
    
    IVitals:
    ${vitalsText}

    Reported Body Issues (Current):
    ${partsText || 'None selected'}

    ${ayurvedicText}

    Recent History & Context:
    ${recentHistory || 'No recent history available.'}

    Research Context (Bookmarks):
    ${bookmarksText || 'No bookmarks available. Use general medical knowledge.'}
    `;

    if (carePlan) {
      prompt += `
      \n----\n
      IMPORTANT: A physician-created care plan is already in place. Your analysis should align with, and build upon, this plan. Do not contradict it.
      Care Plan:
      ${carePlan}
      \n----
      `;
    }

    return prompt;
  }
}