import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/patient_types.dart';
import 'clinical_intelligence_service.dart';

class ExportService {
  Future<void> downloadAsPdf({
    required Patient patient,
    required Map<AnalysisLens, String> reports,
  }) async {
    final pdf = pw.Document();

    final timestamp = DateTime.now().toString().split('.')[0];
    
    // Add page for the report
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Letterhead
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Pocket Gull', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                      pw.Text('Clinical Intelligence Platform', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Generated: $timestamp', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                      pw.Text('Report Type: Comprehensive Clinical Analysis', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                      pw.Text('Confidential – Clinical Use Only', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                    ],
                  )
                ]
              )
            ),
            
            pw.SizedBox(height: 20),
            
            // Patient Banner
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                color: PdfColors.grey100,
              ),
              padding: const pw.EdgeInsets.all(12),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  _buildPatientField('Patient Name', patient.name),
                  _buildPatientField('Age/Gender', '${patient.age} / ${patient.gender}'),
                  _buildPatientField('Report Date', DateTime.now().toString().split(' ')[0]),
                ]
              )
            ),
            
            pw.SizedBox(height: 20),
            
            // AI Disclaimer
            pw.Container(
              padding: const pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#FFFBEB'),
                border: pw.Border(left: pw.BorderSide(color: PdfColor.fromHex('#D97706'), width: 3)),
              ),
              child: pw.Text(
                'AI-Assisted Clinical Report. This document was generated by the PocketGull AI engine. All recommendations are advisory and must be reviewed by a licensed healthcare professional.',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              )
            ),
            
            pw.SizedBox(height: 20),
            
            // Lenses
            ...AnalysisLens.values.where((lens) => reports.containsKey(lens) && reports[lens]!.isNotEmpty).map((lens) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.all(8),
                    color: PdfColors.grey200,
                    child: pw.Text(lens.title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Text(reports[lens]!, style: const pw.TextStyle(fontSize: 12)),
                  pw.SizedBox(height: 20),
                ]
              );
            }).toList(),
          ];
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 20),
            child: pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
            ),
          );
        },
      )
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'PocketGull_Report_${patient.name.replaceAll(' ', '_')}.pdf',
    );
  }

  pw.Widget _buildPatientField(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label.toUpperCase(), style: pw.TextStyle(fontSize: 8, color: PdfColors.grey700, fontWeight: pw.FontWeight.bold)),
        pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
      ]
    );
  }
}
