import '../models/social_vector.dart';

class SocialGravitationService {
  static final List<SocialVector> defaultSocialVectors = [
    const SocialVector(
      id: 'soc-1',
      name: 'Sunrise Ocean Vagal Breathwork Circle',
      category: 'event',
      type: 'gravitate',
      coherenceMatchPercent: 96,
      distanceMiles: 1.8,
      emoji: '🌅',
      biomarkerImpact: 'Triggers parasympathetic vagal stimulation, lowers serum cortisol by 24%, and boosts 10Hz alpha waves.',
      energeticRationale: 'Sattva Guna pure energy; nourishes Heart Blood and grounds erratic Shen.',
      tcmAyurvedicMatch: 'Sattva (Purity) & Heart Shen Harmony',
      locationName: 'Pacific Cove Sanctuary',
    ),
    const SocialVector(
      id: 'soc-2',
      name: 'Farm-to-Table Organic Nootropic Potluck',
      category: 'community',
      type: 'gravitate',
      coherenceMatchPercent: 92,
      distanceMiles: 3.2,
      emoji: '🥗',
      biomarkerImpact: 'Upregulates gut microbiome diversity, increases SCFA production, and elevates serotonin.',
      energeticRationale: 'Tonifies TCM Spleen Qi and earth element; fosters empathetic social bonding.',
      tcmAyurvedicMatch: 'Spleen Qi & Ojas Building',
      locationName: 'Green Meadow Organic Commons',
    ),
    const SocialVector(
      id: 'soc-3',
      name: '528 Hz Solfeggio Sound Healing & Tea Ceremony',
      category: 'event',
      type: 'gravitate',
      coherenceMatchPercent: 95,
      distanceMiles: 2.5,
      emoji: '🫖',
      biomarkerImpact: 'Increases heart rate variability (HRV) and promotes prefrontal delta-theta synchronization.',
      energeticRationale: 'Harmonizes kidney Jing essence and opens the pericardium meridian.',
      tcmAyurvedicMatch: 'Jing Preservation & Shen Tranquilization',
      locationName: 'Lotus Temple Tea House',
    ),
    const SocialVector(
      id: 'soc-4',
      name: 'Late-Night High-Noise Club & Alcohol Lounge',
      category: 'avoidance',
      type: 'avoid',
      coherenceMatchPercent: 12,
      distanceMiles: 4.1,
      emoji: '🍻',
      biomarkerImpact: 'Suppresses slow-wave delta glymphatic clearance and surges nocturnal cortisol.',
      energeticRationale: 'Rajasic/Tamasic chaos; disturbs Liver Qi and induces Shen agitation.',
      tcmAyurvedicMatch: 'Rajasic Agitation & Liver Fire Spike',
      locationName: 'Neon Underground Nightclub',
    ),
    const SocialVector(
      id: 'soc-5',
      name: 'Heavy Traffic Smog & High-EMF Commercial Zone',
      category: 'environment',
      type: 'avoid',
      coherenceMatchPercent: 18,
      distanceMiles: 5.0,
      emoji: '🏭',
      biomarkerImpact: 'Increases systemic inflammatory cytokines (IL-6, TNF-alpha) and disrupts cell membrane polarization.',
      energeticRationale: 'Depletes Lung Qi and weakens Wei Qi defensive protective aura.',
      tcmAyurvedicMatch: 'Lung Qi Deficiency & Toxic Heat',
      locationName: 'Industrial Highway Corridor',
    ),
  ];

  static final List<HobbyVector> defaultHobbies = [
    const HobbyVector(
      id: 'hob-1',
      name: 'Bonsai Cultivation & Horticulture',
      emoji: '🪴',
      timeCommitment: '2 hrs/week',
      difficulty: 'Beginner',
      characterTrait: 'Patience & Long-term Mindfulness',
      clinicalBenefits: 'Reduces salivary cortisol arousal by 22% and calms prefrontal chatter.',
      energeticSynergy: 'Balances Wood element; grounds erratic Vata energy.',
    ),
    const HobbyVector(
      id: 'hob-2',
      name: 'Ceramic Pottery & Clay Sculpting',
      emoji: '🏺',
      timeCommitment: '3 hrs/week',
      difficulty: 'Intermediate',
      characterTrait: 'Somatic Emotional Grounding',
      clinicalBenefits: 'Activates bilateral brain hemispheres and reduces amygdala fear reactivity.',
      energeticSynergy: 'Tonifies Earth element and Spleen Qi; anchors floating Shen.',
    ),
    const HobbyVector(
      id: 'hob-3',
      name: 'Acoustic String Instrument (Lute/Harp)',
      emoji: '🪕',
      timeCommitment: '4 hrs/week',
      difficulty: 'Intermediate',
      characterTrait: 'Neuroplastic Harmony & Expression',
      clinicalBenefits: 'Increases 10Hz occipital alpha power and triggers endorphin release.',
      energeticSynergy: 'Expands Heart Pericardium energy and enhances Sattvic clarity.',
    ),
    const HobbyVector(
      id: 'hob-4',
      name: 'Wild Botanical Foraging & Herbal Crafting',
      emoji: '🌿',
      timeCommitment: '2 hrs/week',
      difficulty: 'Beginner',
      characterTrait: 'Ecological Intelligence & Vitality',
      clinicalBenefits: 'Phytoncide inhalation boosts Natural Killer (NK) immune cell counts.',
      energeticSynergy: 'Harmonizes Five Elements (Wu Xing) and preserves Kidney Jing.',
    ),
    const HobbyVector(
      id: 'hob-5',
      name: 'Animal Rescue Volunteering',
      emoji: '🐕',
      timeCommitment: '2 hrs/week',
      difficulty: 'Beginner',
      characterTrait: 'Altruistic Compassion & Purpose',
      clinicalBenefits: 'Surges plasma oxytocin levels and lowers resting heart rate.',
      energeticSynergy: 'Embodiment of Sattva Guna (Purity); nourishes Heart Blood.',
    ),
  ];
}
